services:
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./nginx/ssl/certificate.crt:/etc/nginx/ssl/certificate.crt:ro
      - ./nginx/ssl/private.key:/etc/nginx/ssl/private.key:ro
    networks:
      - public
    depends_on:
      - nestjs
  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - private
    volumes:
      # MySQL의 실제 데이터 파일은 여기에 저장됨
      - hsu_auto_scheduler_mysql_data:/var/lib/mysql

      # 컨테이너 최초 실행 시 init.sql 자동 실행
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

      # SQL 파일 접근용
      - ./sql:/sql
  fastapi:
    build:
      context: ./ortools-scheduler
      dockerfile: dockerfile.prod
    networks:
      - private
  nestjs:
    build:
      context: ./hsu-auto-scheduler-be
      dockerfile: dockerfile.prod
    # expose:
    #   - ${NESTJS_PORT}
    ports:
      - 5000:5000
    networks:
      - public
      - private
    environment:
      PORT: ${NESTJS_PORT}
      ENV: ${ENV}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      FAST_API_BASE_URL: ${FAST_API_BASE_URL}
networks:
  public:
  private:

volumes:
  hsu_auto_scheduler_mysql_data:
